-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgOT/g/I/kOX3ibPrT
s3ptFJP2DaoInDE+5e71PfISDRWgCgYIKoZIzj0DAQehRANCAAR5msHyLSP/GN6a
3obPunOT6NcJgWsQn7qsL1b/Qb+FGKbJ+Gvc6pCF+XCSXSKQjupCvKECUGC53pqK
XYvkd+2T
-----END PRIVATE KEY-----